
services:
  credit-risk-api:
    build: .
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
    volumes:
      - .:/app
